apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argo-deployments
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: arn:aws:eks:ap-southeast-1:675629362743:cluster/test-cluster
    namespace: default
  syncPolicy:
     automated:
       prune: true
       selfHeal: true
