apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edge-project
  namespace: argocd
spec:
  description: Project for edge live sync workloads
  sourceRepos:
    - "*"
  destinations:
    - namespace: edge
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

